# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.

[build]
  command = "rmdir -rf site && CI=false && python3 publish.py posts/*"
  publish = "site"