# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.

[build]
  command = "CI=false && rm -rf site && python3 publish.py posts/*"
  publish = "site/"